environment:
  matrix:
    - python_version: 2.7.10
      cassandra_version: 3.0.3
platform:
  - x64
install:
  - ps: .\appveyor.ps1
build_script:
  - cmd: python setup.py install --no-cython
test_script:
  - ps: |
      nosetests -s -v --with-ignore-docstrings --with-xunit --xunit-file=unit_results.xml .\tests\unit

      exit 0
after_test:
  -ps: |
    $wc = New-Object 'System.Net.WebClient'
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\unit_results.xml))
cache:
  - C:\Users\appveyor\.m2
  - C:\ProgramData\chocolatey\bin
  - C:\ProgramData\chocolatey\lib
  - C:\Users\appveyor\jce_policy-1.7.0.zip
  - C:\Users\appveyor\jce_policy-1.8.0.zip
  - C:\Users\appveyor\.ccm\repository
  - C:\Users\appveyor\ccm